### ISSUE TITLE
Next enhancement ?

### ISSUE THREAD

**Issue by alexisju** [NerosTie/emojione#2]
Maybe you need to add some CSS (to the object class `.emojione`):  no problem to have unicode emoji (ie `🌴`) converted into image (🌴), but if you use shortname (ie `:palm_tree:`), the emoji converted is very big (100% svg size).

Do you plan already some enhancements, like : 
- ascii smilies conversion  (http://git.emojione.com/demos/2.1.4/ascii-smileys.html)
- shortcode autocomplete  (http://git.emojione.com/demos/2.1.4/autocomplete.html) (without that we need to copy/paste unicode emojis from other websites or memorise shortcodes, what is not very convenient).

[Copy/pasted feedback  from https://github.com/shaarli/Shaarli/issues/545#issuecomment-214775453 )

**Comment by NerosTie** [comment]
The issue with shortname is fixed, can you try?

**Comment by alexisju** [comment]
Right! Fixed :-)

**Comment by NerosTie** [comment]
ASCII conversion works. Can you try? But be aware, you can't have a smiley alone on a line.

To activate it, change `false` to `true` in `emojione.js`

**Comment by alexisju** [comment]
It work (but in dont understand your warning).

**Comment by NerosTie** [comment]
If you put a smiley alone, like this: 

:)

It will not be converted.

**Comment by alexisju** [comment]
On my instance, both works

**Comment by NerosTie** [comment]
Not me, weird...

The autocomplete.js is huge! 250 Ko :worried:

**Comment by alexisju** [comment]
Maybe it is better to not include it into this plugin (for people like you using browser plugin), but create another plugin to load if people need it?
(or make a custom version with less autocomplete sugestion) ?

You can also simple add in the readme some exemple to Firefox/Chrome addons...

**Comment by NerosTie** [comment]
It works! And I like it. Even on a smartphone, it's pretty cool.

But unfortunately, this is big! The autocomplete.js itself is big but you also need 2 external jquery javascripts as dependencies...

385 Ko for the all thing.

Also, it works only in the `Description` area. It could be nice to have it in the `Tags` area too.

Is it worth it to have a separate plugin? Or just one plugin but I comment the whole thing about autocomplete?

**Comment by alexisju** [comment]
Minified version of js can reduce size and improve loading time ?

**Comment by alexisju** [comment]
It seems autocomplete could also work with zepto.js (9 ko) instead jquery.

and jquery.textcomplete.min.js 18.4 KB

Minified version of autocomplete is around 230 ko

**Comment by NerosTie** [comment]
And around 50 Ko if gzipped (with closure)

Do you think it's better to have everything self-hosted? Or is it ok to call them from the outside?

**Comment by alexisju** [comment]
Personnaly i prefer to have all librairies self-hosted. It is not a performance matter but about privacy and tracking.

**Comment by NerosTie** [comment]
Well, it works even without jquery. So we can delete it.

So now the question is: 230ko, is it too big for this plugin?

**Comment by alexisju** [comment]
I don't know, i think it is not too much (if loadded in footer). The scripts just need to be loaded once, after the browser keep it in the cache.

**Comment by NerosTie** [comment]
Ok, let's try then. I will self-host `emojione.min.js` too (188ko). Gzipped, it should be ok. If people complain I will see. 
The only thin that I can't self-host are the svg and the png, this is way too big.

But I will comment the autocomplete, because maybe not everybody will like it.

Also, can you tell me what happen if you put a shortname as a tag?

**Comment by alexisju** [comment]
(By self hosting, i mean to included into this repository; each shaarli instance is self hosted)

**Comment by NerosTie** [comment]
Yes, this is my definition of self-hosting too.

**Comment by NerosTie** [comment]
New version is out! 

Don't forget to edit `emojione.php` and `js/emojione.js` to activate all the functions.

Tell me what you think and can you tell me what happen if you put a shortname as a tag?

**Comment by alexisju** [comment]
Broken!

You need to put  emojione.min.js before emojione.js to render emojis

I don't get autocomplete

Bonus: .dropdown-menu css alterate my shaarli's template (albinomouse). They use the same class' name.

**Comment by NerosTie** [comment]
Not broken anymore :wink:

**Comment by NerosTie** [comment]
For `.dropdown-menu`, I have to edit `autocomplete.css` and `textcomplete.min.js`. I don't like this idea for future updates (they are unmodified versions of the originals).

**Comment by alexisju** [comment]
Ok, not broken anymore, but autocomplete still not working.

**Comment by NerosTie** [comment]
It works for me. But I have jquery with my theme. Maybe it doesn't work with zepto.js.

Can you comment the line with zepto.js in `emojione.php` and add this instead:
`$data['js_files'][] = 'https://code.jquery.com/jquery-2.2.3.min.js';`

And tell me if it works.

**Comment by alexisju** [comment]
I just tryed, but it didnt work.

However, in same time i have weird things. The plugin seems no work anymore on my instance..

I don't understand why. I cleared the tmp files.. and tryed on another test instance.. without better result.

**Comment by NerosTie** [comment]
You say it works with jquery but in the same time the plugin do no work anymore? I don't understand.

**Comment by alexisju** [comment]
Sorry it didnt.

**Comment by alexisju** [comment]
Ok i know why. I desactivated markdown plugin.

**Comment by NerosTie** [comment]
Well, autocomplete do not work with the default theme either... (I'm using the material theme)

**Comment by alexisju** [comment]
(i'm doing my test with default template ;) )

**Comment by NerosTie** [comment]
Ha! That's why! Unfortunately, I have no solution in mind :disappointed:

**Comment by alexisju** [comment]
Using awesomplete  (shaarli's autocomplete js for tags) ?

**Comment by NerosTie** [comment]
I don't understand your question.

**Comment by alexisju** [comment]
Awesomplete (http://leaverou.github.io/awesomplete/) is the js library used by shaarli to suggest (and autocomplete) tags. Maybe it could be used also the the emoji's shortcode list ?

**Comment by NerosTie** [comment]
It would be more complicated to implement it, I think.
Autocomplete seems to be more powerful for emojis than awesomplete would be.
With autocomplete, you can search `:food` which is not an emoji but a tag for a family of emojis.

But there are other bugs: https://github.com/NerosTie/emojione/issues

**Comment by alexisju** [comment]
Ok, for now i can use browser addon :-) Its fine too

**Comment by NerosTie** [comment]
What do you call "browser addon"?

**Comment by alexisju** [comment]
However, if autocomplete is broken with defaut shaarli, maybe it is better to have a "clean" plugin which just enable emoji (and another plugin to enable autocomplete in your theme).

At least comment also `$data['css_files'][] = PluginManager::$PLUGINS_PATH . '/emojione/css/autocomplete.css';` by defaut

Browser addon: Firefox/Chrome extension

**Comment by alexisju** [comment]
Another thing, if you fix autocomplete : maybe it is better if the autocomplete can insert unicode emoji (not shortcode), it will fit better in RSS or if we disable the plugin.

**Comment by NerosTie** [comment]
> Ok, for now i can use browser addon :-) Its fine too

Autocomplete do not work with the theme you use but it works with the browser addon? The extension on chrome is basically a page in html.

> maybe it is better to have a "clean" plugin which just enable emoji (and another plugin to enable autocomplete in your theme).

It's not supposed to be broken forever :wink:. I will let the autocomplete and ASCII Smiley commented for now. To have them in option it's a good solution, I think.

> Another thing, if you fix autocomplete : maybe it is better if the autocomplete can insert unicode emoji (not shortcode), it will fit better in RSS or if we disable the plugin.

Autocomplete is based on shortnames, so I don't think it will be easy to change it. But I agree, for RSS it would be better. That's why I'm reticent to use shortnames for now. (but a good RSS aggregator could have an addon for emojione too :smile: )

**Comment by alexisju** [comment]
> Autocomplete do not work with the theme you use but it works with the browser addon? 

This extension work very well : http://johannh.me/emoji-helper/

**Comment by NerosTie** [comment]
Use this: https://chrome.google.com/webstore/detail/emoji-keyboard-2016-by-em/ipdjnhgkpapgippgcgkfcbpdpcgifncb

This is better, and it's the official plugin for emojione :)

**Comment by NerosTie** [comment]
I'm closing this issue. The bug is fixed and all the enhancements are implemented even if some work is needed to have a full compatibility with the most famous themes. Feel free to open a new thread but only for specifics issues, please.
