### ISSUE TITLE
HTML end tag breaks ASCII conversion

### ISSUE THREAD

**Issue by NerosTie** [NerosTie/emojione#5]
~~If you use https://github.com/kalvn/Shaarli-Material there are some issues:~~

~~\* if you put a smiley alone on a line like `:)`, it's not converted if markdown is activated~~
~~\* if you put a smiley like `:)` in the tags area, it's not converted~~

~~It works well with the default theme.~~

EDIT: see: https://github.com/Ranks/emojione/issues/54

**Comment by kalvn** [comment]
As explained here: https://github.com/kalvn/Shaarli-Material/issues/47 it's a bug of the library emojione which was referenced here https://github.com/Ranks/emojione/issues/54 one year ago but still not fixed.
