### ISSUE TITLE
Support the live preview function for Shortnames

### ISSUE THREAD

**Issue by NerosTie** [NerosTie/emojione#7]
There is a live preview function for shortnames:

http://git.emojione.com/demos/2.1.4/live-preview.html

``` javascript
<script type="text/javascript">
  $(document).ready(function() {
    $("#inputText").on('keyup change input',function(e) {
      var source = $('#inputText').val();
      var preview = emojione.toImage(source);
      $('#outputText').html(preview);
    });
  });
</script>
```

If someone knows how to implement it... :smiley:

**Comment by kalvn** [comment]
I don't think that input text and live output can be in the same HTML element. In their example, the output is just a div, not the initial input.

**Comment by NerosTie** [comment]
Yes, I know what you mean. This could work if the editor and the rendered text was separated. I think I will close it.
